# @baseurl = http://119.12.166.178:1010/api/v1
@baseurl = http://127.0.0.1:1010/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTA0NzFjZDIwNTA5ZDM3ZjQwZGQzOGMiLCJuYW1lIjoiUnVkeSBDYW5hIiwidXNlcm5hbWUiOiJSdWR5IENhbmEiLCJpYXQiOjE2OTQ3OTQxNjQsImV4cCI6MTY5NDg4MDU2NH0.eSAldNcPE4m6-kabjTD6UYKI7tYWFcARBrVTz46JEBw

### USER LOGIN
POST {{baseurl}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "rudy.cana@gmail.com",
    "password": "Rowdee@14"
}


### USER REGISTER
POST {{baseurl}}/auth/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name" : "Rudy Cana",
  "email" : "rudy.cana@gmail.com",
  "password": "Rowdee@14",
  "confirm_password": "Rowdee@14"
}


### USER LOGOUT
POST {{baseurl}}/auth/logout HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json


